### ISSUE TITLE
DeriveKeyPair Implementation?

### ISSUE THREAD

**Issue by Aurvandill** [dajiaji/pyhpke#125]
Hello,

First of all thanks for the great work.

And another question are there any plans to implement the `DeriveKeyPair` function specified in the RFC?
Or did i maybe miss something?

with best regards
Aurvandil

**Comment by Aurvandill** [comment]
oh nvm i just saw Issue #9
sorry for bothering

**Comment by dajiaji** [comment]
@Aurvandill No problem.
Thank you for filing your requirement.
I'll implement it as soon as possible.
