### ISSUE TITLE
KEM._nsecret Question

### ISSUE THREAD

**Issue by Aurvandill** [dajiaji/pyhpke#134]
a short Question in Regards to the `_nsecret`Attribute. Is that attribute the `Nsk` from the RFC?
if yes then shouldn't it be 

* `56` for `KEMId.DHKEM_X448_HKDF_SHA512` instead of `64`
* `66` for `KEMId.DHKEM_P521_HKDF_SHA512` instead of `64`

?

(according to https://www.rfc-editor.org/rfc/rfc9180.html#name-key-encapsulation-mechanism)

with best regards
Aurvandill

**Comment by dajiaji** [comment]
`_nsecret` is the `Nsecret` from the RFC.

Is there any problem?

**Comment by Aurvandill** [comment]
I need the `Nsk` for the derive Key Pair function. an i misused the `_nsecret`. i will add the `Nsk` as `_nsk` Attribute in my PR if thats fine :)
