### ISSUE TITLE
Elliptic Curve `to_private_bytes` uses DER Encoding and does not dump the private_numbers().private_value

### ISSUE THREAD

**Issue by Aurvandill** [dajiaji/pyhpke#138]
By mistake i made a mistake when implementing the serialization of the Elliptic Curve Private Keys. Instead of just dumping the `private_numbers().private_value` i encoded the key with the DER encoding.

this mistake will be fixed by PR #137

Sorry for the mistake

with best regards
Aurvandill

**Comment by Aurvandill** [comment]
@dajiaji sorry for the inconvenience but did you already have time to look at this?

**Comment by dajiaji** [comment]
Resolved by #137
