### ISSUE TITLE
Fix `CipherSuite` return type in docstring

### ISSUE THREAD

**Issue by ArmandsAnt** [dajiaji/pyhpke#230]
Return type should be `CipherSuite` instead. 
IDEs show this as an incorrect type warning.

https://github.com/dajiaji/pyhpke/blob/e9d157fc15d7392eb0064aa8785a0cf89aa10938/pyhpke/cipher_suite.py#L31-L41

**Comment by dajiaji** [comment]
Thank you for the report. I've fixed it on #231.

**Comment by ArmandsAnt** [comment]
Docstring return type should be changed from `bytes` to `CipyherSuite` as well:

https://github.com/dajiaji/pyhpke/blob/e9d157fc15d7392eb0064aa8785a0cf89aa10938/pyhpke/cipher_suite.py#L39-L41

**Comment by dajiaji** [comment]
Thanks. Fixed by #232
